image: node:10.16.0@sha256:7cae3b2b42bde73b68e82fbd949cfff5b43546c2daabba3e95c8a603a04eec09

cache:
  key: purty-v1
  paths:
    - .stack-root
    - .stack-work

variables:
  LC_ALL: C.UTF-8
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root
  
stages:
  - build

Build purty:
  before_script:
    - mkdir --parents $HOME/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - ci/install-stack.sh --verbose
    - stack setup
  script:
    - ci/lint/stylish-haskell.sh --verbose
    - ci/lint/hlint.sh --verbose
    - stack build --copy-bins --coverage --local-bin-path bin --no-run-tests --test
    - stack build --copy-bins --coverage --local-bin-path bin/linux --no-run-tests --test
    - make test STACK_BUILDFLAGS=--coverage
  stage: build
