image: node:10.16.0@sha256:7cae3b2b42bde73b68e82fbd949cfff5b43546c2daabba3e95c8a603a04eec09

cache:
  key: purty-v1
  paths:
    - ${CI_PROJECT_DIR}/.bazel-cache

variables:
  BAZEL_CONFIG: '--config=gitlabci'
  LC_ALL: C.UTF-8

stages:
  - build

Build purty:
  script:
    - make coverage
  stage: build
