image: haskell:8.2.1

cache:
  paths:
    - .stack-root
    - .stack-work

variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root
  
stages:
  - install
  - build
  - test

Install Haskell dependencies:
  script: stack setup
  stage: install

Compile Haskell:
  script: stack build --no-run-tests --test
  stage: build

Run golden tests:
  script: stack build --test
  stage: test
