image: buildpack-deps:18.04

cache:
  key: purty
  paths:
    - .stack-root
    - .stack-work

variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root
  
stages:
  - build

Build purty:
  before_script:
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - apt-get update
    - apt-get install --yes haskell-stack nodejs
    - stack upgrade --binary-only
    - export PATH=$HOME/.local/bin:$PATH
    - stack setup
  script:
    - ci/lint/stylish-haskell.sh --verbose
    - ci/lint/hlint.sh --verbose
    - stack build --copy-bins --coverage --local-bin-path bin --no-run-tests --test
    - stack build --copy-bins --coverage --local-bin-path bin/linux --no-run-tests --test
    - stack build --coverage --test
    - echo Testing binary interface
    - test/acceptance.sh --verbose
    - echo Testing npm interface
    - test/acceptance.sh --purty $(pwd)/bin/purty.js --verbose
  stage: build
