image: haskell:8.2.1

cache:
  key: purty
  paths:
    - .stack-root
    - .stack-work

variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root
  
stages:
  - build

Build purty:
  script:
    - stack --system-ghc setup
    - stack --system-ghc build --copy-bins --coverage --local-bin-path bin --no-run-tests --test
    - stack --system-ghc build --coverage --test
    - test/acceptance.sh --verbose
  stage: build
