image: ubuntu:18.04

cache:
  key: purty
  paths:
    - $HOME/.local/bin
    - .stack-root
    - .stack-work

variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root
  
stages:
  - build

Build purty:
  before_script:
    - ci/install-stack.sh --verbose
    - stack setup
  script:
    - ci/lint/stylish-haskell.sh --verbose
    - ci/lint/hlint.sh --verbose
    - stack build --copy-bins --coverage --local-bin-path bin --no-run-tests --test
    - stack build --coverage --test
    - test/acceptance.sh --verbose
  stage: build
