image: fpco/stack-build:lts-10.10

cache:
  paths:
    - .stack-root
    - .stack-work

variables:
  STACK_ROOT: .stack-root
  
stages:
  - install
  - build
  - test

Install Haskell dependencies:
  script: stack setup
  stage: install

Compile Haskell:
  script: stack build --no-run-tests --test
  stage: build

Run golden tests:
  script: stack build --test
  stage: test
