image: haskell:8.2.1

cache:
  key: purty
  paths:
    - .stack-root
    - .stack-work

variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root
  
stages:
  - install
  - build
  - test

Install Haskell dependencies:
  script: stack --system-ghc setup
  stage: install

Compile Haskell:
  script: stack --system-ghc build --no-run-tests --test
  stage: build

Run golden tests:
  script: stack --system-ghc build --test
  stage: test
