image: node:10.16.0@sha256:7cae3b2b42bde73b68e82fbd949cfff5b43546c2daabba3e95c8a603a04eec09

cache:
  key: purty-v1
  paths:
    - ${CI_PROJECT_DIR}/.bazel-cache

variables:
  LC_ALL: C.UTF-8

stages:
  - build

Build purty:
  before_script:
    - make bootstrap
  script:
    - .build/bazel test //...
    - .build/bazel coverage --test_tag_filters -coverage_requires_jvm //...
    - make lint
  stage: build
