before_deploy:
  - tar --create --file purty-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz --directory bin --gzip purty

before_install:
  - ci/install-stack.sh --os ${TRAVIS_OS_NAME} --verbose

cache:
  directories:
    - ${HOME}/.local/bin
    - .stack-root
    - .stack-work

deploy:
  - file: ci/bintray-${TRAVIS_OS_NAME}.json
    key:
      secure: EaX5OWSCJcAB/yRhEWDDZ9dDM9HXzDnyLdWCeLDKpd82X4xSMP9RXvxOSyXm3xCeZZtt+WwPjcfwBBgeVfcmBfUhhfAVDqlToo+Y6WhUDincaaMC77/f6Yq7LP+Bx6eJelUgpaygbiqH2jR2xzEdVPyDYC/npjcVyR96JUK8k5Oj7GmIbkwr2tzAM8cgDJHY2VwR0PeObLK+t1CEAcaYhb6JJ7yPDCr3vPTl6IgUOqGmkaA/gwO7Fx6wFm+HwSEXVWUfz3NHssHUt6tQHv0AjoDLK84v2DBH1hSqYUEEJqr+5dE26k4G0t2BZJnYkzIgu6YO4qGAvtF8PnH//uKcwiJXwZViheCjnPe/h7Kl/RVGms37jbeCOZWKMro5kZosTWjAlT+P5v1C4650MObU4k0SPFmqiT25GEUDZhsy9sc9jWo+Yo7a31jqcCKcAO9PvUQCvxgChV1sV2Bq3axmnI0O2U/9VsskEQQj0pm8VygqC43gTdquVKNu88+c2OnpoZkXrQK6x/34vA97bFkSl2JWIxefXoJ3wKalcd5vp+HcQvm/TAnaYcHAt7ju2P/KRrY1zTo+mLlIX3DNXWfNxjHHJRIwPRuEohxa1vgwjajKv5dKkwDOrXYhC33AEkq06Sgl2jdV3ZoR6U2MaFGi9QcWAkEvBP5DYbboTvFzrOU=
    on:
      repo: joneshf/purty
      tags: true
    provider: bintray
    skip_cleanup: true
    user: joneshf

env:
  global:
    - CASHER_TIME_OUT=1000
    - PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}
    - STACK_ROOT=${TRAVIS_BUILD_DIR}/.stack-root

language: c

notifications:
  webhooks:
    - secure: t8fOnG4eXLO/dHrwEiEDP/l3NhDl4ssm+iFgkxy9Hvj+7ih7kUEL+GGMQ8uWAQfBOxb5m8NGFSdZv61PphZnky/qdcCJihR6TSe90Tls1kUy56ep0B9QRe9PhOdkD8xuRwpbZbkzFY/krxjhJEXObEBqmk7XOXIq/QlLA6Fng3C1GBmvqHvT7DODXZfUi1DqoA09ydwY2S4YTOJtPZUVs760xANup9BzILm007/pDsIws4//B6saQfb6Qzab9OyAD2eitQ+6Fzn3wbqoUsUrEM1yGkJWHiRS+tSSo8/D4rOM9g+Su1+ZjLrp9kHiAToCbZR6rmy7t6X8KzvsIoIVx2CDHuU8JleIpUQ9vwcrmh4eSVc6jZmgm7YfIw4Hww0+vi6nDFnRlGiHrCHi6ZSC6inEoQsxruQcb/3olVXmVrOuwh1LZ1b1cY4VhW3mgF0MTApFt3+JGos1cbA1GFbEZxDb+a6MwXN1jWqg3LdIiYMw/3OW82AKuc3D1cKv41CbVJiu8Ilpkz+whg6PD6KpC09Abqi4mD5wtHpvdWjX93DJk1SshY5L7o3ncrQxUOarVVgNuEsLRtnL0W1XIl2VeBe+grCR1VUeyvo0wPETFEqXUXMYGKyFaC8ZDW1tiz4SkxYNbhgyfDwc9DT7gzVBkN9vWHhO6P2hnqAfogacnMw=

os:
  - linux
  - osx

sudo: false

script:
  - stack setup
  - stack build --copy-bins --coverage --local-bin-path bin --no-run-tests --test
  - stack build --coverage --test
  - test/acceptance.sh --verbose
