build_script:
  - stack setup
  - stack build --copy-bins --coverage --local-bin-path bin --no-run-tests --test
  - stack build --coverage --test

cache:
  - .stack-root
  - .stack-work
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  STACK_ROOT: '%APPVEYOR_BUILD_FOLDER%\.stack-root'

install:
  - chocolatey install haskell-stack --version 1.6.5 --yes

version: '{build}'
