before_deploy:
  - 7z a -so -ttar purty-%APPVEYOR_REPO_TAG_NAME%-win.tar .\bin\purty.exe | 7z a -si purty-%APPVEYOR_REPO_TAG_NAME%-win.tar.gz
  - appveyor PushArtifact purty-%APPVEYOR_REPO_TAG_NAME%-win.tar.gz

build_script:
  - .build\bazel.exe build //:purty-library
  - stack setup
  - make test-golden BINARY=purty.exe

cache:
  - '%APPVEYOR_BUILD_FOLDER%\.bazel-cache'
  - .stack-root
  - .stack-work
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

deploy:
  - api_key:
      secure: y/pMqpeXcoK4ZUAPdF4at7Ji7XjRRa8cOsQtQH8HT+G5mgwh1ctnPt5NqMd3Npcn
    artifact: 'purty-%APPVEYOR_REPO_TAG_NAME%-win.tar.gz'
    on:
      appveyor_repo_tag: true
    package: purty
    provider: BinTray
    publish: true
    repo: generic
    subject: joneshf
    username: joneshf
    version: '%APPVEYOR_REPO_TAG_NAME%'

environment:
  PYTHON: C:\Python37
  STACK_ROOT: '%APPVEYOR_BUILD_FOLDER%\.stack-root'
  TEST_TMPDIR: '%APPVEYOR_BUILD_FOLDER%\.bazel-cache'

install:
  - chocolatey install haskell-stack --version 1.9.3 --yes
  - chocolatey install make --version 4.3 --yes
  - make bootstrap OS=windows

version: '{build}'
