author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
executables:
  purty:
    dependencies:
      - base == 4.12.0.0
      - purty
    main: Main.hs
    source-dirs: src
extra-source-files:
  - README.md
ghc-options:
  - -Wall
  - -Wcompat
  # - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-methods
  - -Wredundant-constraints
homepage: https://github.com/joneshf/purty#readme
library:
  dependencies:
    - base == 4.12.0.0
    - bytestring == 0.10.8.2
    - componentm == 0.0.0.2
    - dhall == 1.23.0
    - optparse-applicative == 0.14.3.0
    - purescript == 0.13.2
    - rio == 0.1.9.2
    - text == 1.2.3.1
    - semigroupoids == 5.3.4
  source-dirs: lib
license: BSD3
maintainer: jones3.hardy@gmail.com
name: purty
tests:
  golden:
    dependencies:
      - base == 4.12.0.0
      - bytestring == 0.10.8.2
      - componentm == 0.0.0.2
      - purty
      - rio == 0.1.9.2
      - tasty == 1.2
      - tasty-golden == 2.3.2
      - tasty-hunit == 0.10.0.1
      - text == 1.2.3.1
    main: Main.hs
    source-dirs: test/golden
version: 4.6.0
