author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
executables:
  purty:
    dependencies:
      - base == 4.10.0.0
      - optparse-applicative == 0.14.0.0
      - prettyprinter == 1.1.1
      - purty
      - rio == 0.1.0.0
    main: Main.hs
    source-dirs: src
extra-source-files:
  - README.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-methods
  - -Wredundant-constraints
homepage: https://github.com/joneshf/purty#readme
library:
  dependencies:
    - base == 4.10.0.0
    - containers == 0.5.10.2
    - optparse-applicative == 0.14.0.0
    - parsec == 3.1.11
    - path == 0.6.1
    - path-io == 1.3.3
    - prettyprinter == 1.1.1
    - purescript == 0.11.7
    - rio == 0.1.0.0
    - text == 1.2.2.2
  source-dirs: lib
license: BSD3
maintainer: jones3.hardy@gmail.com
name: purty
tests:
  golden:
    dependencies:
      - base == 4.10.0.0
      - path == 0.6.1
      - path-io == 1.3.3
      - prettyprinter == 1.1.1
      - purty
      - rio == 0.1.0.0
      - tasty == 0.11.2.5
      - tasty-golden == 2.3.1.1
    main: Main.hs
    source-dirs: test/golden
version: '0.1.0.0'
