author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
executables:
  purty:
    dependencies:
      - base == 4.10.0.0
      - microlens-platform == 0.3.9.0
      - mtl == 2.2.1
      - optparse-applicative == 0.14.0.0
      - path == 0.6.1
      - prettyprinter == 1.1.1
      - protolude == 0.2.1
      - purescript == 0.11.7
    main: Main.hs
    source-dirs: src
extra-source-files:
  - README.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-methods
  - -Wredundant-constraints
homepage: https://github.com/joneshf/purty#readme
license: BSD3
maintainer: jones3.hardy@gmail.com
name: purty
version: '0.1.0.0'
