author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
executables:
  purty:
    dependencies:
      - base == 4.10.1.0
      - dhall == 1.14.0
      - directory ==1.3.0.2
      - optparse-applicative == 0.14.2.0
      - path-io == 1.3.3
      - prettyprinter == 1.2.0.1
      - purty
      - rio == 0.1.2.0
    main: Main.hs
    source-dirs: src
extra-source-files:
  - README.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-methods
  - -Wredundant-constraints
homepage: https://github.com/joneshf/purty#readme
library:
  dependencies:
    - base == 4.10.1.0
    - containers == 0.5.10.2
    - dhall == 1.14.0
    - lens == 4.16.1
    - mtl == 2.2.2
    - optparse-applicative == 0.14.2.0
    - optparse-text == 0.1.1.0
    - parsec == 3.1.13.0
    - path == 0.6.1
    - path-io == 1.3.3
    - prettyprinter == 1.2.0.1
    - purescript == 0.12.0
    - rio == 0.1.2.0
    - semigroupoids == 5.2.2
    - text == 1.2.3.0
    - transformers == 0.5.2.0
  source-dirs: lib
license: BSD3
maintainer: jones3.hardy@gmail.com
name: purty
tests:
  golden:
    dependencies:
      - base == 4.10.1.0
      - path == 0.6.1
      - path-io == 1.3.3
      - prettyprinter == 1.2.0.1
      - purty
      - rio == 0.1.2.0
      - tasty == 1.0.1.1
      - tasty-golden == 2.3.1.3
    main: Main.hs
    source-dirs: test/golden
  unit:
    dependencies:
      - base == 4.10.1.0
      - prettyprinter == 1.2.0.1
      - purescript == 0.12.0
      - purty
      - rio == 0.1.2.0
      - tasty == 1.0.1.1
      - tasty-hunit == 0.10.0.1
    main: Main.hs
    source-dirs: test/unit
version: 1.0.1
