# `dhall` and `purescript` have conflicting versions of `network`.
# `dhall` needs `network` for the library.
# `purescript` needs `network` for the executable.
# We don't want to build the executable, but stack forces us to.
# As a hack, we relax all version bounds so `network` can be whatever `dhall`
# wants it to be.
# We should move off of stack unless it's going to fix this issue.
# Nix ought to be able to handle this.
allow-newer: true
extra-deps:
  - componentm-0.0.0.2@sha256:d15df070056810a512183021d95af6fc99a4ff96a26352de4fe46b92ebc84728
  - dhall-1.23.0
  - dhall-json-1.2.8
  - git: https://github.com/purescript/purescript.git
    commit: b7b47b236e9892675c2e7854630f1ae5e219479c
  - repline-0.2.1.0@sha256:0f8e92d78e771afb9d41243c2b6ab9609fe02f94e676fae3caed66fa4ce09b18
  - rio-0.1.9.2
  - teardown-0.5.0.1@sha256:b7a6812637f79d81632bb7adebc5ad9a96fffacf3e5f655d5bf21728bd3786f9
packages:
  - .
resolver: lts-13.12
