flags: {}
packages:
- .
extra-deps:
- Win32-notify-0.3.0.3
- dhall-1.13.1
- formatting-6.3.4
- pipes-http-1.0.5
- prettyprinter-1.2.0.1
- purescript-0.11.7
- repline-0.1.7.0
- rio-0.1.0.0
- typed-process-0.2.2.0
- unliftio-0.2.6.0
- unliftio-core-0.1.1.0
resolver: nightly-2017-09-10
